
package unisagui;

/**
 * @author Davide
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    
    private static GameFrame instance;
    
    private GameFrame() {
        initComponents();
    }
    
    public static synchronized GameFrame getInstance(){
        if (instance == null)
            instance = new GameFrame();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExamDialog = new javax.swing.JDialog();
        ExamPanel = new javax.swing.JPanel();
        ProfLabel = new javax.swing.JLabel();
        StudentLabel = new javax.swing.JLabel();
        NameOfExamLabel = new javax.swing.JLabel();
        LevelOfQuestionLabel = new javax.swing.JLabel();
        ExamScrollPane = new javax.swing.JScrollPane();
        ExamTextArea = new javax.swing.JTextArea();
        FirstAnswer = new javax.swing.JButton();
        SecondAnswer = new javax.swing.JButton();
        ThirdAnswer = new javax.swing.JButton();
        FourthAnswer = new javax.swing.JButton();
        ConfirmAnswer = new javax.swing.JButton();
        MainMenuDialog = new javax.swing.JDialog();
        MainMenuPanel = new javax.swing.JPanel();
        MainMenuLabel = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        NewGameButton = new javax.swing.JButton();
        ResumeGameButton = new javax.swing.JButton();
        CreditsButton = new javax.swing.JButton();
        InventoryDialog = new javax.swing.JDialog();
        InventoryPanel = new javax.swing.JPanel();
        InventoryLabel = new javax.swing.JLabel();
        IconLabel1 = new javax.swing.JLabel();
        IDLabel1 = new javax.swing.JLabel();
        IconLabel2 = new javax.swing.JLabel();
        IDLabel2 = new javax.swing.JLabel();
        IDLabel3 = new javax.swing.JLabel();
        IconLabel3 = new javax.swing.JLabel();
        IconLabel4 = new javax.swing.JLabel();
        IDLabel4 = new javax.swing.JLabel();
        IconLabel5 = new javax.swing.JLabel();
        IDLabel5 = new javax.swing.JLabel();
        IconLabel6 = new javax.swing.JLabel();
        IDLabel6 = new javax.swing.JLabel();
        IDLabel7 = new javax.swing.JLabel();
        IconLabel7 = new javax.swing.JLabel();
        IconLabel8 = new javax.swing.JLabel();
        IDLabel8 = new javax.swing.JLabel();
        IconLabel9 = new javax.swing.JLabel();
        IDLabel9 = new javax.swing.JLabel();
        IconLabel10 = new javax.swing.JLabel();
        IconLabel11 = new javax.swing.JLabel();
        IDLabel10 = new javax.swing.JLabel();
        IDLabel11 = new javax.swing.JLabel();
        IDLabel12 = new javax.swing.JLabel();
        IconLabel12 = new javax.swing.JLabel();
        IconLabel13 = new javax.swing.JLabel();
        IDLabel13 = new javax.swing.JLabel();
        IconLabel14 = new javax.swing.JLabel();
        IDLabel14 = new javax.swing.JLabel();
        IDLabel15 = new javax.swing.JLabel();
        IconLabel15 = new javax.swing.JLabel();
        IconLabel16 = new javax.swing.JLabel();
        IDLabel16 = new javax.swing.JLabel();
        IconLabel17 = new javax.swing.JLabel();
        IDLabel17 = new javax.swing.JLabel();
        IDLabel18 = new javax.swing.JLabel();
        IDLabel19 = new javax.swing.JLabel();
        IconLabel18 = new javax.swing.JLabel();
        IconLabel19 = new javax.swing.JLabel();
        IDLabel20 = new javax.swing.JLabel();
        IconLabel20 = new javax.swing.JLabel();
        IDLabel21 = new javax.swing.JLabel();
        IDLabel22 = new javax.swing.JLabel();
        IconLabel21 = new javax.swing.JLabel();
        IconLabel22 = new javax.swing.JLabel();
        IconLabel23 = new javax.swing.JLabel();
        IDLabel23 = new javax.swing.JLabel();
        IconLabel24 = new javax.swing.JLabel();
        IDLabel24 = new javax.swing.JLabel();
        IDLabel25 = new javax.swing.JLabel();
        IDLabel26 = new javax.swing.JLabel();
        IconLabel25 = new javax.swing.JLabel();
        IconLabel26 = new javax.swing.JLabel();
        IDLabel27 = new javax.swing.JLabel();
        IconLabel27 = new javax.swing.JLabel();
        IDLabel28 = new javax.swing.JLabel();
        IconLabel28 = new javax.swing.JLabel();
        InventoryPageButton = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        SettingsDialog = new javax.swing.JDialog();
        SettingsPanel = new javax.swing.JPanel();
        SettingsLayer = new javax.swing.JLabel();
        AudioButton = new javax.swing.JButton();
        MusicButton = new javax.swing.JButton();
        LanguageButton = new javax.swing.JButton();
        KeyboardButton = new javax.swing.JButton();
        ReturnToMainMenuButton = new javax.swing.JButton();
        GamePanel = new javax.swing.JPanel();
        DialogScrollPane = new javax.swing.JScrollPane();
        DialogTextArea = new javax.swing.JTextArea();
        HudPanel = new javax.swing.JPanel();
        LevelLabel = new javax.swing.JLabel();
        MoneyIcon = new javax.swing.JLabel();
        MoneyLabel = new javax.swing.JLabel();
        EnergyProgressBar = new javax.swing.JProgressBar();
        EnergyIcon = new javax.swing.JLabel();
        StressIcon = new javax.swing.JLabel();
        HungerIcon = new javax.swing.JLabel();
        StressProgressBar = new javax.swing.JProgressBar();
        HungerProgressBar = new javax.swing.JProgressBar();

        ExamPanel.setMaximumSize(new java.awt.Dimension(500, 500));
        ExamPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        ExamPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        ProfLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/FoggiaIcon.jpg"))); // NOI18N
        ProfLabel.setText("jLabel1");
        ProfLabel.setMaximumSize(new java.awt.Dimension(75, 75));
        ProfLabel.setMinimumSize(new java.awt.Dimension(75, 75));
        ProfLabel.setPreferredSize(new java.awt.Dimension(75, 75));

        StudentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/StudentIcon.jpg"))); // NOI18N
        StudentLabel.setText("jLabel2");
        StudentLabel.setMaximumSize(new java.awt.Dimension(75, 75));
        StudentLabel.setMinimumSize(new java.awt.Dimension(75, 75));
        StudentLabel.setPreferredSize(new java.awt.Dimension(75, 75));

        NameOfExamLabel.setText("ExamName");
        NameOfExamLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        NameOfExamLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        NameOfExamLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        LevelOfQuestionLabel.setText("LevelOfQuestion");
        LevelOfQuestionLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        LevelOfQuestionLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        LevelOfQuestionLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        ExamScrollPane.setHorizontalScrollBar(null);

        ExamTextArea.setEditable(false);
        ExamTextArea.setColumns(20);
        ExamTextArea.setRows(5);
        ExamTextArea.setMaximumSize(new java.awt.Dimension(300, 100));
        ExamTextArea.setMinimumSize(new java.awt.Dimension(300, 100));
        ExamTextArea.setPreferredSize(new java.awt.Dimension(300, 100));
        ExamScrollPane.setViewportView(ExamTextArea);

        FirstAnswer.setText("jButton1");
        FirstAnswer.setMaximumSize(new java.awt.Dimension(300, 25));
        FirstAnswer.setMinimumSize(new java.awt.Dimension(300, 25));
        FirstAnswer.setPreferredSize(new java.awt.Dimension(300, 25));

        SecondAnswer.setText("jButton1");
        SecondAnswer.setMaximumSize(new java.awt.Dimension(300, 25));
        SecondAnswer.setMinimumSize(new java.awt.Dimension(300, 25));
        SecondAnswer.setPreferredSize(new java.awt.Dimension(300, 25));

        ThirdAnswer.setText("jButton1");
        ThirdAnswer.setMaximumSize(new java.awt.Dimension(300, 25));
        ThirdAnswer.setMinimumSize(new java.awt.Dimension(300, 25));
        ThirdAnswer.setPreferredSize(new java.awt.Dimension(300, 25));

        FourthAnswer.setText("jButton1");
        FourthAnswer.setMaximumSize(new java.awt.Dimension(300, 25));
        FourthAnswer.setMinimumSize(new java.awt.Dimension(300, 25));
        FourthAnswer.setPreferredSize(new java.awt.Dimension(300, 25));

        ConfirmAnswer.setText("Confirm");
        ConfirmAnswer.setMaximumSize(new java.awt.Dimension(125, 25));
        ConfirmAnswer.setMinimumSize(new java.awt.Dimension(125, 25));
        ConfirmAnswer.setPreferredSize(new java.awt.Dimension(125, 25));
        ConfirmAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExamPanelLayout = new javax.swing.GroupLayout(ExamPanel);
        ExamPanel.setLayout(ExamPanelLayout);
        ExamPanelLayout.setHorizontalGroup(
            ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamPanelLayout.createSequentialGroup()
                .addGroup(ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ExamPanelLayout.createSequentialGroup()
                        .addComponent(ProfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ExamPanelLayout.createSequentialGroup()
                                .addComponent(NameOfExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(LevelOfQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ExamScrollPane)))
                    .addComponent(SecondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(StudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExamPanelLayout.setVerticalGroup(
            ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamPanelLayout.createSequentialGroup()
                .addGroup(ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExamPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ProfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExamPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameOfExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelOfQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(ExamScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(FirstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(SecondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ThirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(FourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(ExamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        ConfirmAnswer.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout ExamDialogLayout = new javax.swing.GroupLayout(ExamDialog.getContentPane());
        ExamDialog.getContentPane().setLayout(ExamDialogLayout);
        ExamDialogLayout.setHorizontalGroup(
            ExamDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ExamDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExamDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ExamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExamDialogLayout.setVerticalGroup(
            ExamDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ExamDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExamDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ExamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainMenuPanel.setMaximumSize(new java.awt.Dimension(600, 750));
        MainMenuPanel.setMinimumSize(new java.awt.Dimension(600, 750));

        MainMenuLabel.setText("                   MAIN MENU");
        MainMenuLabel.setMaximumSize(new java.awt.Dimension(200, 75));
        MainMenuLabel.setMinimumSize(new java.awt.Dimension(200, 75));
        MainMenuLabel.setPreferredSize(new java.awt.Dimension(200, 75));

        SettingsButton.setText("SETT");
        SettingsButton.setMaximumSize(new java.awt.Dimension(75, 75));
        SettingsButton.setMinimumSize(new java.awt.Dimension(75, 75));
        SettingsButton.setPreferredSize(new java.awt.Dimension(75, 75));
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("EXIT");
        ExitButton.setMaximumSize(new java.awt.Dimension(75, 75));
        ExitButton.setMinimumSize(new java.awt.Dimension(75, 75));
        ExitButton.setPreferredSize(new java.awt.Dimension(75, 75));

        NewGameButton.setText("NEW GAME");
        NewGameButton.setMaximumSize(new java.awt.Dimension(200, 50));
        NewGameButton.setMinimumSize(new java.awt.Dimension(200, 50));
        NewGameButton.setPreferredSize(new java.awt.Dimension(200, 50));
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });

        ResumeGameButton.setText("RESUME GAME");
        ResumeGameButton.setMaximumSize(new java.awt.Dimension(200, 50));
        ResumeGameButton.setMinimumSize(new java.awt.Dimension(200, 50));
        ResumeGameButton.setPreferredSize(new java.awt.Dimension(200, 50));
        ResumeGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeGameButtonActionPerformed(evt);
            }
        });

        CreditsButton.setText("CREDITS");
        CreditsButton.setMaximumSize(new java.awt.Dimension(200, 50));
        CreditsButton.setMinimumSize(new java.awt.Dimension(200, 50));
        CreditsButton.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuPanelLayout.createSequentialGroup()
                        .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResumeGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreditsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(NewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ResumeGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(CreditsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout MainMenuDialogLayout = new javax.swing.GroupLayout(MainMenuDialog.getContentPane());
        MainMenuDialog.getContentPane().setLayout(MainMenuDialogLayout);
        MainMenuDialogLayout.setHorizontalGroup(
            MainMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(MainMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainMenuDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MainMenuDialogLayout.setVerticalGroup(
            MainMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(MainMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainMenuDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        InventoryPanel.setMaximumSize(new java.awt.Dimension(400, 450));
        InventoryPanel.setMinimumSize(new java.awt.Dimension(400, 450));

        InventoryLabel.setText("                          INVENTORY");
        InventoryLabel.setMaximumSize(new java.awt.Dimension(250, 25));
        InventoryLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        InventoryLabel.setPreferredSize(new java.awt.Dimension(250, 25));

        IconLabel1.setText("jLabel2");
        IconLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel1.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel1.setText("jLabel3");
        IDLabel1.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel1.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel1.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel2.setText("jLabel2");
        IconLabel2.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel2.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel2.setText("jLabel3");
        IDLabel2.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel2.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel2.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel3.setText("jLabel3");
        IDLabel3.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel3.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel3.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel3.setText("jLabel2");
        IconLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel3.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel4.setText("jLabel2");
        IconLabel4.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel4.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel4.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel4.setText("jLabel3");
        IDLabel4.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel4.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel4.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel5.setText("jLabel2");
        IconLabel5.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel5.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel5.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel5.setText("jLabel3");
        IDLabel5.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel5.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel5.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel6.setText("jLabel2");
        IconLabel6.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel6.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel6.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel6.setText("jLabel3");
        IDLabel6.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel6.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel6.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel7.setText("jLabel3");
        IDLabel7.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel7.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel7.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel7.setText("jLabel2");
        IconLabel7.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel7.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel7.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel8.setText("jLabel2");
        IconLabel8.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel8.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel8.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel8.setText("jLabel3");
        IDLabel8.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel8.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel8.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel9.setText("jLabel2");
        IconLabel9.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel9.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel9.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel9.setText("jLabel3");
        IDLabel9.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel9.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel9.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel10.setText("jLabel2");
        IconLabel10.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel10.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel10.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel11.setText("jLabel2");
        IconLabel11.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel11.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel11.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel10.setText("jLabel3");
        IDLabel10.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel10.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel10.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel11.setText("jLabel3");
        IDLabel11.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel11.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel11.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel12.setText("jLabel3");
        IDLabel12.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel12.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel12.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel12.setText("jLabel2");
        IconLabel12.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel12.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel12.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel13.setText("jLabel2");
        IconLabel13.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel13.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel13.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel13.setText("jLabel3");
        IDLabel13.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel13.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel13.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel14.setText("jLabel2");
        IconLabel14.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel14.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel14.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel14.setText("jLabel3");
        IDLabel14.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel14.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel14.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel15.setText("jLabel3");
        IDLabel15.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel15.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel15.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel15.setText("jLabel2");
        IconLabel15.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel15.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel15.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel16.setText("jLabel2");
        IconLabel16.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel16.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel16.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel16.setText("jLabel3");
        IDLabel16.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel16.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel16.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel17.setText("jLabel2");
        IconLabel17.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel17.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel17.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel17.setText("jLabel3");
        IDLabel17.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel17.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel17.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel18.setText("jLabel3");
        IDLabel18.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel18.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel18.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel19.setText("jLabel3");
        IDLabel19.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel19.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel19.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel18.setText("jLabel2");
        IconLabel18.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel18.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel18.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel19.setText("jLabel2");
        IconLabel19.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel19.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel19.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel20.setText("jLabel3");
        IDLabel20.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel20.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel20.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel20.setText("jLabel2");
        IconLabel20.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel20.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel20.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel21.setText("jLabel3");
        IDLabel21.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel21.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel21.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel22.setText("jLabel3");
        IDLabel22.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel22.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel22.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel21.setText("jLabel2");
        IconLabel21.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel21.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel21.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel22.setText("jLabel2");
        IconLabel22.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel22.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel22.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel23.setText("jLabel2");
        IconLabel23.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel23.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel23.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel23.setText("jLabel3");
        IDLabel23.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel23.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel23.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel24.setText("jLabel2");
        IconLabel24.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel24.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel24.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel24.setText("jLabel3");
        IDLabel24.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel24.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel24.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel25.setText("jLabel3");
        IDLabel25.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel25.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel25.setPreferredSize(new java.awt.Dimension(50, 25));

        IDLabel26.setText("jLabel3");
        IDLabel26.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel26.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel26.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel25.setText("jLabel2");
        IconLabel25.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel25.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel25.setPreferredSize(new java.awt.Dimension(50, 50));

        IconLabel26.setText("jLabel2");
        IconLabel26.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel26.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel26.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel27.setText("jLabel3");
        IDLabel27.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel27.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel27.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel27.setText("jLabel2");
        IconLabel27.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel27.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel27.setPreferredSize(new java.awt.Dimension(50, 50));

        IDLabel28.setText("jLabel3");
        IDLabel28.setMaximumSize(new java.awt.Dimension(50, 25));
        IDLabel28.setMinimumSize(new java.awt.Dimension(50, 25));
        IDLabel28.setPreferredSize(new java.awt.Dimension(50, 25));

        IconLabel28.setText("jLabel2");
        IconLabel28.setMaximumSize(new java.awt.Dimension(50, 50));
        IconLabel28.setMinimumSize(new java.awt.Dimension(50, 50));
        IconLabel28.setPreferredSize(new java.awt.Dimension(50, 50));

        InventoryPageButton.setText("PAGE");
        InventoryPageButton.setMaximumSize(new java.awt.Dimension(50, 25));
        InventoryPageButton.setMinimumSize(new java.awt.Dimension(50, 25));
        InventoryPageButton.setPreferredSize(new java.awt.Dimension(50, 25));

        NextButton.setText("NE");
        NextButton.setMaximumSize(new java.awt.Dimension(50, 25));
        NextButton.setMinimumSize(new java.awt.Dimension(50, 25));
        NextButton.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout InventoryPanelLayout = new javax.swing.GroupLayout(InventoryPanel);
        InventoryPanel.setLayout(InventoryPanelLayout);
        InventoryPanelLayout.setHorizontalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryPanelLayout.createSequentialGroup()
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(InventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(InventoryPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        InventoryPanelLayout.setVerticalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(InventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryPanelLayout.createSequentialGroup()
                        .addComponent(IconLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IconLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IDLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InventoryPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout InventoryDialogLayout = new javax.swing.GroupLayout(InventoryDialog.getContentPane());
        InventoryDialog.getContentPane().setLayout(InventoryDialogLayout);
        InventoryDialogLayout.setHorizontalGroup(
            InventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(InventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InventoryDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        InventoryDialogLayout.setVerticalGroup(
            InventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(InventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InventoryDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        SettingsPanel.setMaximumSize(new java.awt.Dimension(600, 750));
        SettingsPanel.setMinimumSize(new java.awt.Dimension(600, 750));

        SettingsLayer.setText("                     SETTINGS");
        SettingsLayer.setMaximumSize(new java.awt.Dimension(200, 75));
        SettingsLayer.setMinimumSize(new java.awt.Dimension(200, 75));
        SettingsLayer.setPreferredSize(new java.awt.Dimension(200, 75));

        AudioButton.setText("Sounds\n");
        AudioButton.setMaximumSize(new java.awt.Dimension(75, 75));
        AudioButton.setMinimumSize(new java.awt.Dimension(75, 75));
        AudioButton.setPreferredSize(new java.awt.Dimension(75, 75));
        AudioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioButtonActionPerformed(evt);
            }
        });

        MusicButton.setText("Music\n");
        MusicButton.setMaximumSize(new java.awt.Dimension(75, 75));
        MusicButton.setMinimumSize(new java.awt.Dimension(75, 75));
        MusicButton.setPreferredSize(new java.awt.Dimension(75, 75));

        LanguageButton.setText("LANGUAGE");
        LanguageButton.setMaximumSize(new java.awt.Dimension(200, 50));
        LanguageButton.setMinimumSize(new java.awt.Dimension(200, 50));
        LanguageButton.setPreferredSize(new java.awt.Dimension(200, 50));
        LanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageButtonActionPerformed(evt);
            }
        });

        KeyboardButton.setText("KEYBOARD SETTINGS");
        KeyboardButton.setMaximumSize(new java.awt.Dimension(200, 50));
        KeyboardButton.setMinimumSize(new java.awt.Dimension(200, 50));
        KeyboardButton.setPreferredSize(new java.awt.Dimension(200, 50));

        ReturnToMainMenuButton.setText("MAIN MENU");
        ReturnToMainMenuButton.setMaximumSize(new java.awt.Dimension(200, 50));
        ReturnToMainMenuButton.setMinimumSize(new java.awt.Dimension(200, 50));
        ReturnToMainMenuButton.setPreferredSize(new java.awt.Dimension(200, 50));
        ReturnToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnToMainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LanguageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(AudioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(MusicButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SettingsLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KeyboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(SettingsLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AudioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusicButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(LanguageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(KeyboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ReturnToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout SettingsDialogLayout = new javax.swing.GroupLayout(SettingsDialog.getContentPane());
        SettingsDialog.getContentPane().setLayout(SettingsDialogLayout);
        SettingsDialogLayout.setHorizontalGroup(
            SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SettingsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SettingsDialogLayout.setVerticalGroup(
            SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SettingsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HNTBAE\n"); // NOI18N
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 750));
        setName("PrincipalJFrame\n"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 750));

        GamePanel.setBackground(new java.awt.Color(51, 255, 0));
        GamePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GamePanel.setMaximumSize(new java.awt.Dimension(500, 500));
        GamePanel.setMinimumSize(new java.awt.Dimension(500, 500));
        GamePanel.setPreferredSize(new java.awt.Dimension(500, 500));

        DialogTextArea.setEditable(false);
        DialogTextArea.setColumns(20);
        DialogTextArea.setRows(5);
        DialogTextArea.setMaximumSize(new java.awt.Dimension(200, 100));
        DialogTextArea.setMinimumSize(new java.awt.Dimension(200, 100));
        DialogTextArea.setPreferredSize(new java.awt.Dimension(200, 100));
        DialogScrollPane.setViewportView(DialogTextArea);

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(DialogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(DialogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        HudPanel.setMaximumSize(new java.awt.Dimension(600, 175));
        HudPanel.setMinimumSize(new java.awt.Dimension(600, 175));
        HudPanel.setPreferredSize(new java.awt.Dimension(600, 175));

        LevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        LevelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        LevelLabel.setText(".");
        LevelLabel.setMaximumSize(new java.awt.Dimension(225, 25));
        LevelLabel.setMinimumSize(new java.awt.Dimension(225, 25));
        LevelLabel.setPreferredSize(new java.awt.Dimension(225, 25));

        MoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        MoneyIcon.setText("jLabel2");
        MoneyIcon.setMaximumSize(new java.awt.Dimension(25, 25));
        MoneyIcon.setMinimumSize(new java.awt.Dimension(25, 25));
        MoneyIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        MoneyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        MoneyLabel.setText("jLabel3");
        MoneyLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        MoneyLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        MoneyLabel.setPreferredSize(new java.awt.Dimension(125, 25));

        EnergyProgressBar.setMaximumSize(new java.awt.Dimension(150, 25));
        EnergyProgressBar.setMinimumSize(new java.awt.Dimension(150, 25));
        EnergyProgressBar.setPreferredSize(new java.awt.Dimension(150, 25));

        EnergyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        EnergyIcon.setText("jLabel2");
        EnergyIcon.setMaximumSize(new java.awt.Dimension(25, 25));
        EnergyIcon.setMinimumSize(new java.awt.Dimension(25, 25));
        EnergyIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        StressIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        StressIcon.setText("jLabel2");
        StressIcon.setMaximumSize(new java.awt.Dimension(25, 25));
        StressIcon.setMinimumSize(new java.awt.Dimension(25, 25));
        StressIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        HungerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unisagui/RossoLabel.PNG"))); // NOI18N
        HungerIcon.setText("jLabel2");
        HungerIcon.setMaximumSize(new java.awt.Dimension(25, 25));
        HungerIcon.setMinimumSize(new java.awt.Dimension(25, 25));
        HungerIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        StressProgressBar.setMaximumSize(new java.awt.Dimension(150, 25));
        StressProgressBar.setMinimumSize(new java.awt.Dimension(150, 25));
        StressProgressBar.setPreferredSize(new java.awt.Dimension(150, 25));

        HungerProgressBar.setMaximumSize(new java.awt.Dimension(150, 25));
        HungerProgressBar.setMinimumSize(new java.awt.Dimension(150, 25));
        HungerProgressBar.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout HudPanelLayout = new javax.swing.GroupLayout(HudPanel);
        HudPanel.setLayout(HudPanelLayout);
        HudPanelLayout.setHorizontalGroup(
            HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HudPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HudPanelLayout.createSequentialGroup()
                        .addComponent(MoneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(MoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HungerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StressProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HudPanelLayout.createSequentialGroup()
                        .addComponent(LevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(EnergyProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HungerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StressIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnergyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        HudPanelLayout.setVerticalGroup(
            HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HudPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EnergyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EnergyProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LevelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StressProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MoneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StressIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(HudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HungerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HungerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(GamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(GamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(618, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmAnswerActionPerformed

    private void AudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AudioButtonActionPerformed

    private void LanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanguageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanguageButtonActionPerformed

    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewGameButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void ResumeGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeGameButtonActionPerformed

    private void ReturnToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnToMainMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnToMainMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton AudioButton;
    protected javax.swing.JButton ConfirmAnswer;
    protected javax.swing.JButton CreditsButton;
    protected javax.swing.JScrollPane DialogScrollPane;
    protected javax.swing.JTextArea DialogTextArea;
    protected javax.swing.JLabel EnergyIcon;
    protected javax.swing.JProgressBar EnergyProgressBar;
    protected javax.swing.JDialog ExamDialog;
    protected javax.swing.JPanel ExamPanel;
    protected javax.swing.JScrollPane ExamScrollPane;
    protected javax.swing.JTextArea ExamTextArea;
    protected javax.swing.JButton ExitButton;
    protected javax.swing.JButton FirstAnswer;
    protected javax.swing.JButton FourthAnswer;
    protected javax.swing.JPanel GamePanel;
    protected javax.swing.JPanel HudPanel;
    protected javax.swing.JLabel HungerIcon;
    protected javax.swing.JProgressBar HungerProgressBar;
    protected javax.swing.JLabel IDLabel1;
    protected javax.swing.JLabel IDLabel10;
    protected javax.swing.JLabel IDLabel11;
    protected javax.swing.JLabel IDLabel12;
    protected javax.swing.JLabel IDLabel13;
    protected javax.swing.JLabel IDLabel14;
    protected javax.swing.JLabel IDLabel15;
    protected javax.swing.JLabel IDLabel16;
    protected javax.swing.JLabel IDLabel17;
    protected javax.swing.JLabel IDLabel18;
    protected javax.swing.JLabel IDLabel19;
    protected javax.swing.JLabel IDLabel2;
    protected javax.swing.JLabel IDLabel20;
    protected javax.swing.JLabel IDLabel21;
    protected javax.swing.JLabel IDLabel22;
    protected javax.swing.JLabel IDLabel23;
    protected javax.swing.JLabel IDLabel24;
    protected javax.swing.JLabel IDLabel25;
    protected javax.swing.JLabel IDLabel26;
    protected javax.swing.JLabel IDLabel27;
    protected javax.swing.JLabel IDLabel28;
    protected javax.swing.JLabel IDLabel3;
    protected javax.swing.JLabel IDLabel4;
    protected javax.swing.JLabel IDLabel5;
    protected javax.swing.JLabel IDLabel6;
    protected javax.swing.JLabel IDLabel7;
    protected javax.swing.JLabel IDLabel8;
    protected javax.swing.JLabel IDLabel9;
    protected javax.swing.JLabel IconLabel1;
    protected javax.swing.JLabel IconLabel10;
    protected javax.swing.JLabel IconLabel11;
    protected javax.swing.JLabel IconLabel12;
    protected javax.swing.JLabel IconLabel13;
    protected javax.swing.JLabel IconLabel14;
    protected javax.swing.JLabel IconLabel15;
    protected javax.swing.JLabel IconLabel16;
    protected javax.swing.JLabel IconLabel17;
    protected javax.swing.JLabel IconLabel18;
    protected javax.swing.JLabel IconLabel19;
    protected javax.swing.JLabel IconLabel2;
    protected javax.swing.JLabel IconLabel20;
    protected javax.swing.JLabel IconLabel21;
    protected javax.swing.JLabel IconLabel22;
    protected javax.swing.JLabel IconLabel23;
    protected javax.swing.JLabel IconLabel24;
    protected javax.swing.JLabel IconLabel25;
    protected javax.swing.JLabel IconLabel26;
    protected javax.swing.JLabel IconLabel27;
    protected javax.swing.JLabel IconLabel28;
    protected javax.swing.JLabel IconLabel3;
    protected javax.swing.JLabel IconLabel4;
    protected javax.swing.JLabel IconLabel5;
    protected javax.swing.JLabel IconLabel6;
    protected javax.swing.JLabel IconLabel7;
    protected javax.swing.JLabel IconLabel8;
    protected javax.swing.JLabel IconLabel9;
    protected javax.swing.JDialog InventoryDialog;
    protected javax.swing.JLabel InventoryLabel;
    protected javax.swing.JLabel InventoryPageButton;
    protected javax.swing.JPanel InventoryPanel;
    protected javax.swing.JButton KeyboardButton;
    protected javax.swing.JButton LanguageButton;
    protected javax.swing.JLabel LevelLabel;
    protected javax.swing.JLabel LevelOfQuestionLabel;
    protected javax.swing.JDialog MainMenuDialog;
    protected javax.swing.JLabel MainMenuLabel;
    protected javax.swing.JPanel MainMenuPanel;
    protected javax.swing.JLabel MoneyIcon;
    protected javax.swing.JLabel MoneyLabel;
    protected javax.swing.JButton MusicButton;
    protected javax.swing.JLabel NameOfExamLabel;
    protected javax.swing.JButton NewGameButton;
    protected javax.swing.JButton NextButton;
    protected javax.swing.JLabel ProfLabel;
    protected javax.swing.JButton ResumeGameButton;
    protected javax.swing.JButton ReturnToMainMenuButton;
    protected javax.swing.JButton SecondAnswer;
    protected javax.swing.JButton SettingsButton;
    protected javax.swing.JDialog SettingsDialog;
    protected javax.swing.JLabel SettingsLayer;
    protected javax.swing.JPanel SettingsPanel;
    protected javax.swing.JLabel StressIcon;
    protected javax.swing.JProgressBar StressProgressBar;
    protected javax.swing.JLabel StudentLabel;
    protected javax.swing.JButton ThirdAnswer;
    // End of variables declaration//GEN-END:variables
}
